/**
 * Mode B — 30 blog post outlines (seeded as drafts).
 * Each post has a complete outline structure, placeholder SEO fields,
 * 5 FAQ stubs, and image suggestions.
 * Activate with: SEED_MODE=B STRAPI_ADMIN_PASSWORD=xxx npx ts-node scripts/seed/index.ts
 */

import { createDraft, getId } from '../client'
import { h2, h3, p, ul } from '../helpers'

interface BlogPostSeedB {
  title: string
  slug: string
  excerpt: string
  seo_title: string
  seo_description: string
  reading_time: number
  ranchi_reference: boolean
  categories: string[]
  tags: string[]
  featured_image_alt: string
  featured_image_suggestion: string
  stock_search_keywords: string[]
  content: unknown[]
  faqs: { question: string; answer: string }[]
}

// ── 30 Mode B Outline Posts ────────────────────────────────────────────────

const postsModeB: BlogPostSeedB[] = [
  // ── POST 1 ──────────────────────────────────────────────────────────────
  {
    title: 'What Is Physiotherapy? A Complete Guide for Patients in Ranchi',
    slug: 'what-is-physiotherapy-guide-ranchi',
    excerpt:
      'Discover what physiotherapy is, how it works, and why patients in Ranchi choose it for pain relief, recovery, and long-term wellness.',
    seo_title: '// FILL: ~60 chars — e.g. "What Is Physiotherapy? Complete Patient Guide | The RNB Clinic"',
    seo_description:
      '// FILL: ~155 chars — cover what physiotherapy is, what to expect, mention RNB Clinic Ranchi',
    reading_time: 7,
    ranchi_reference: true,
    categories: ['Physiotherapy Basics'],
    tags: ['physiotherapy', 'ranchi', 'physiotherapy basics'],
    featured_image_alt: '// FILL: descriptive alt text for hero image',
    featured_image_suggestion:
      'Physiotherapist explaining treatment to patient, bright modern clinic, blue/white colour scheme',
    stock_search_keywords: ['physiotherapy clinic', 'physical therapy consultation', 'physiotherapist patient'],
    content: [
      h2('What Is Physiotherapy?'),
      p('[OUTLINE: 150-word introduction — define physiotherapy, mention evidence-based practice, mention RNB Clinic Ranchi]'),
      h2('What Does a Physiotherapist Do?'),
      p('[OUTLINE: 200 words — assessment, diagnosis, treatment planning, patient education]'),
      ul(
        '[LIST ITEM: clinical assessment skills]',
        '[LIST ITEM: manual therapy techniques]',
        '[LIST ITEM: therapeutic exercise prescription]',
        '[LIST ITEM: electrotherapy modalities]',
        '[LIST ITEM: patient education and self-management]'
      ),
      h2('Common Conditions Treated by Physiotherapy'),
      p('[OUTLINE: 200 words — list 8+ conditions: back pain, sports injuries, stroke rehab, etc.]'),
      h2('Types of Physiotherapy Techniques'),
      p('[OUTLINE: 200 words — manual therapy, exercise therapy, electrotherapy, dry needling, hydrotherapy]'),
      h2('Why Choose Physiotherapy Over Medication?'),
      p('[OUTLINE: 200 words — evidence-based argument, long-term benefits, no side effects]'),
      h2('What to Expect at Your First Appointment at RNB Clinic'),
      p('[OUTLINE: 150 words — initial assessment process, treatment plan discussion, duration]'),
      h2('Conclusion'),
      p('[OUTLINE: 100 words — summary + CTA to book appointment at The RNB Clinic Ranchi]'),
    ],
    faqs: [
      { question: 'Is physiotherapy painful?', answer: '[FILL: 40-60 words]' },
      { question: 'How many physiotherapy sessions will I need?', answer: '[FILL: 40-60 words]' },
      { question: 'Do I need a doctor referral to see a physiotherapist?', answer: '[FILL: 40-60 words]' },
      { question: 'What should I wear to a physiotherapy appointment?', answer: '[FILL: 40-60 words]' },
      { question: 'Is physiotherapy covered by health insurance in India?', answer: '[FILL: 40-60 words]' },
    ],
  },

  // ── POST 2 ──────────────────────────────────────────────────────────────
  {
    title: 'Back Pain Treatment Without Surgery: How Physiotherapy Helps',
    slug: 'back-pain-treatment-without-surgery-physiotherapy',
    excerpt:
      'Most back pain can be treated effectively without surgery. Learn how physiotherapy addresses the root cause and restores long-term function.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 8,
    ranchi_reference: false,
    categories: ['Back & Spine'],
    tags: ['back pain', 'spine', 'rehabilitation', 'manual therapy'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist treating patient lower back pain, manual therapy technique, clinical setting',
    stock_search_keywords: ['back pain physiotherapy', 'lower back treatment', 'spinal rehabilitation'],
    content: [
      h2('Why Back Pain Is So Common'),
      p('[OUTLINE: 150 words — statistics, sedentary lifestyle, desk work, poor posture]'),
      h2('When Is Surgery Actually Necessary?'),
      p('[OUTLINE: 150 words — red flags list, cauda equina, when to refer to surgeon]'),
      h2('How Physiotherapy Treats Back Pain'),
      p('[OUTLINE: 200 words — assessment, core strengthening, manual therapy, postural correction]'),
      h2('Types of Back Pain Physiotherapy Treats'),
      ul(
        '[LIST ITEM: acute muscle strain]',
        '[LIST ITEM: disc herniation / slipped disc]',
        '[LIST ITEM: facet joint pain]',
        '[LIST ITEM: lumbar spondylosis]',
        '[LIST ITEM: sacroiliac joint dysfunction]'
      ),
      h2('Core Strengthening: The Foundation of Back Pain Recovery'),
      p('[OUTLINE: 200 words — transversus abdominis, multifidus, progressive loading]'),
      h2('Manual Therapy Techniques for Back Pain'),
      p('[OUTLINE: 150 words — joint mobilisation, soft tissue massage, dry needling]'),
      h2('Self-Management Tips'),
      p('[OUTLINE: 150 words — posture at desk, sleeping positions, gentle stretches]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA to book at RNB Clinic]'),
    ],
    faqs: [
      { question: 'How long does physiotherapy for back pain take?', answer: '[FILL]' },
      { question: 'Can physiotherapy make back pain worse?', answer: '[FILL]' },
      { question: 'What is the best sleeping position for back pain?', answer: '[FILL]' },
      { question: 'Should I rest or exercise with back pain?', answer: '[FILL]' },
      { question: 'When should I see a doctor for back pain?', answer: '[FILL]' },
    ],
  },

  // ── POST 3 ──────────────────────────────────────────────────────────────
  {
    title: 'Neck Pain & Cervical Spondylosis: Physiotherapy Explained',
    slug: 'neck-pain-cervical-spondylosis-physiotherapy',
    excerpt:
      'Cervical spondylosis is one of the most common causes of chronic neck pain. Physiotherapy offers evidence-based treatment to reduce pain and restore movement.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Back & Spine'],
    tags: ['neck pain', 'cervical spondylosis', 'spine', 'manual therapy'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist treating patient neck with manual therapy, traction technique, clinical setting',
    stock_search_keywords: ['neck pain treatment', 'cervical spondylosis physiotherapy', 'cervical traction'],
    content: [
      h2('What Is Cervical Spondylosis?'),
      p('[OUTLINE: 150 words — age-related degeneration of cervical discs and facet joints]'),
      h2('Symptoms of Cervical Spondylosis'),
      ul('[LIST ITEM: neck pain and stiffness]', '[LIST ITEM: headaches from cervicogenic origin]', '[LIST ITEM: arm pain / radiculopathy]', '[LIST ITEM: tingling or numbness in hands]', '[LIST ITEM: reduced range of motion]'),
      h2('How Physiotherapy Assesses and Treats Neck Pain'),
      p('[OUTLINE: 200 words — postural assessment, joint mobilisation, traction, nerve mobilisation]'),
      h2('Exercise Therapy for Cervical Spondylosis'),
      p('[OUTLINE: 200 words — deep neck flexors, capital flexion exercises, postural muscles]'),
      h2('Ergonomic and Lifestyle Modifications'),
      p('[OUTLINE: 150 words — monitor height, pillow choice, phone use habits]'),
      h2('When to See a Specialist'),
      p('[OUTLINE: 100 words — myelopathy warning signs, when to escalate]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'Can cervical spondylosis be cured?', answer: '[FILL]' },
      { question: 'Is cervical traction safe?', answer: '[FILL]' },
      { question: 'What pillow is best for cervical spondylosis?', answer: '[FILL]' },
      { question: 'How long does it take to recover from cervical spondylosis?', answer: '[FILL]' },
      { question: 'Should I use a neck collar for cervical pain?', answer: '[FILL]' },
    ],
  },

  // ── POST 4 ──────────────────────────────────────────────────────────────
  {
    title: 'Sports Injury Recovery: When to See a Physiotherapist',
    slug: 'sports-injury-recovery-when-to-see-physiotherapist',
    excerpt:
      'Not all sports injuries need rest. Learn which injuries benefit from immediate physiotherapy and how to speed up your return to sport safely.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Sports & Rehabilitation'],
    tags: ['sports injury', 'rehabilitation', 'knee pain', 'manual therapy'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist assessing athlete knee injury, sports clinic, blue treatment room',
    stock_search_keywords: ['sports injury physiotherapy', 'athlete rehabilitation', 'return to sport'],
    content: [
      h2('Common Sports Injuries That Need Physiotherapy'),
      p('[OUTLINE: 150 words — ACL, muscle strains, ankle sprains, rotator cuff, stress fractures]'),
      h2('PRICE vs POLICE Protocol: Which Is Current Best Practice?'),
      p('[OUTLINE: 200 words — evolution from RICE to POLICE to PEACE & LOVE protocols]'),
      h2('When to See a Physiotherapist Immediately'),
      ul('[LIST ITEM: inability to bear weight]', '[LIST ITEM: joint locking or giving way]', '[LIST ITEM: visible deformity]', '[LIST ITEM: severe swelling within minutes]', '[LIST ITEM: numbness or pins and needles]'),
      h2('The Physiotherapy Assessment for Sports Injuries'),
      p('[OUTLINE: 200 words — history, biomechanical analysis, special tests, functional testing]'),
      h2('Phases of Sports Injury Rehabilitation'),
      p('[OUTLINE: 200 words — acute, subacute, functional rehab, return-to-sport testing]'),
      h2('Return-to-Sport: How Do You Know When You\'re Ready?'),
      p('[OUTLINE: 150 words — hop tests, strength ratios, psychological readiness]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'Should I apply ice or heat to a sports injury?', answer: '[FILL]' },
      { question: 'How soon after injury should I see a physiotherapist?', answer: '[FILL]' },
      { question: 'Can I still train with a sports injury?', answer: '[FILL]' },
      { question: 'How long does sports injury physiotherapy take?', answer: '[FILL]' },
      { question: 'What is the difference between a strain and a sprain?', answer: '[FILL]' },
    ],
  },

  // ── POST 5 ──────────────────────────────────────────────────────────────
  {
    title: 'Knee Pain Relief Through Exercise and Manual Therapy',
    slug: 'knee-pain-relief-exercise-manual-therapy',
    excerpt:
      'Knee pain affects millions worldwide. Discover how targeted exercise therapy and manual therapy can provide lasting relief without surgery.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Health & Lifestyle'],
    tags: ['knee pain', 'joints', 'rehabilitation', 'exercise therapy'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist guiding patient through knee exercises, rehabilitation gym, clinical setting',
    stock_search_keywords: ['knee pain treatment', 'knee physiotherapy', 'knee rehabilitation exercises'],
    content: [
      h2('Why Does Knee Pain Occur?'),
      p('[OUTLINE: 150 words — anatomy, common causes: osteoarthritis, patellofemoral, ligament, meniscus]'),
      h2('Diagnosing the Cause of Knee Pain'),
      p('[OUTLINE: 150 words — physiotherapy assessment, special tests, imaging guidance]'),
      h2('Exercise Therapy for Knee Pain'),
      p('[OUTLINE: 200 words — quadriceps strengthening, VMO activation, hip strengthening rationale]'),
      h3('Beginner Exercise Programme'),
      ul('[LIST ITEM: straight leg raises]', '[LIST ITEM: mini squats]', '[LIST ITEM: hip abduction in side-lying]', '[LIST ITEM: calf raises]', '[LIST ITEM: hamstring stretches]'),
      h2('Manual Therapy Techniques for the Knee'),
      p('[OUTLINE: 150 words — patellar mobilisation, tibiofemoral joint mobilisation, soft tissue release]'),
      h2('Managing Knee Osteoarthritis Long-Term'),
      p('[OUTLINE: 200 words — weight management, exercise as medicine, injection alternatives]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'Is walking good or bad for knee pain?', answer: '[FILL]' },
      { question: 'Can physiotherapy delay or avoid knee replacement surgery?', answer: '[FILL]' },
      { question: 'What exercises should I avoid with knee pain?', answer: '[FILL]' },
      { question: 'How long does knee pain physiotherapy take?', answer: '[FILL]' },
      { question: 'Should I wear a knee brace?', answer: '[FILL]' },
    ],
  },

  // ── POST 6 ──────────────────────────────────────────────────────────────
  {
    title: 'Frozen Shoulder: Causes, Symptoms & Physiotherapy Treatment',
    slug: 'frozen-shoulder-causes-symptoms-physiotherapy-treatment',
    excerpt:
      'Frozen shoulder (adhesive capsulitis) can cause months of severe pain and stiffness. Physiotherapy is the most effective long-term treatment.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Health & Lifestyle'],
    tags: ['frozen shoulder', 'shoulder', 'manual therapy', 'rehabilitation'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist performing shoulder joint mobilisation on patient, clinical treatment room',
    stock_search_keywords: ['frozen shoulder treatment', 'adhesive capsulitis physiotherapy', 'shoulder stiffness'],
    content: [
      h2('What Is Frozen Shoulder?'),
      p('[OUTLINE: 150 words — adhesive capsulitis, three stages: freezing, frozen, thawing]'),
      h2('Who Gets Frozen Shoulder?'),
      p('[OUTLINE: 150 words — risk factors: diabetes, thyroid, immobilisation, 40-60 age group, women]'),
      h2('Symptoms and Stages'),
      p('[OUTLINE: 200 words — detailed stage descriptions, average duration of each]'),
      h2('Physiotherapy Treatment for Each Stage'),
      p('[OUTLINE: 200 words — stage-appropriate treatment, pain management in freezing, mobilisation in frozen, strengthening in thawing]'),
      h2('Exercises for Frozen Shoulder'),
      ul('[LIST ITEM: pendulum exercises]', '[LIST ITEM: towel stretch behind back]', '[LIST ITEM: wall crawl]', '[LIST ITEM: cross-body stretch]', '[LIST ITEM: external rotation with band]'),
      h2('When Is Injection or Surgery Considered?'),
      p('[OUTLINE: 150 words — corticosteroid injection, hydrodistension, manipulation under anaesthesia]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'How long does frozen shoulder last without treatment?', answer: '[FILL]' },
      { question: 'Can frozen shoulder heal on its own?', answer: '[FILL]' },
      { question: 'Is physiotherapy painful for frozen shoulder?', answer: '[FILL]' },
      { question: 'What is the fastest way to cure frozen shoulder?', answer: '[FILL]' },
      { question: 'Does diabetes cause frozen shoulder?', answer: '[FILL]' },
    ],
  },

  // ── POST 7 ──────────────────────────────────────────────────────────────
  {
    title: 'Sciatica Pain: Physiotherapy vs Medication',
    slug: 'sciatica-pain-physiotherapy-vs-medication',
    excerpt:
      'Sciatica can be debilitating. Compare physiotherapy versus medication approaches and discover why exercise-based treatment leads to better long-term outcomes.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Back & Spine'],
    tags: ['sciatica', 'back pain', 'spine', 'rehabilitation'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Diagram of sciatic nerve pathway, lower back to leg, medical illustration style',
    stock_search_keywords: ['sciatica physiotherapy', 'sciatic nerve pain treatment', 'sciatica exercises'],
    content: [
      h2('What Causes Sciatica?'),
      p('[OUTLINE: 150 words — disc herniation, spinal stenosis, piriformis syndrome, spondylolisthesis]'),
      h2('Sciatica Symptoms: What Does It Feel Like?'),
      p('[OUTLINE: 150 words — shooting pain, burning, tingling, weakness in leg, unilateral nature]'),
      h2('Medication for Sciatica: Short-Term Relief'),
      p('[OUTLINE: 150 words — NSAIDs, muscle relaxants, nerve pain medication, limitations, side effects]'),
      h2('Physiotherapy for Sciatica: Treating the Cause'),
      p('[OUTLINE: 200 words — neural mobilisation, directional preference, McKenzie method, core stability]'),
      h2('Evidence: Physiotherapy vs Medication for Sciatica'),
      p('[OUTLINE: 200 words — research comparison, long-term recurrence rates, surgery avoidance]'),
      h2('Exercises for Sciatica Relief'),
      ul('[LIST ITEM: knee-to-chest stretch]', '[LIST ITEM: piriformis stretch]', '[LIST ITEM: neural flossing / nerve gliding]', '[LIST ITEM: cat-cow mobilisation]', '[LIST ITEM: bird-dog exercise]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'How long does sciatica last?', answer: '[FILL]' },
      { question: 'Should I rest or exercise with sciatica?', answer: '[FILL]' },
      { question: 'What is the best sleeping position for sciatica?', answer: '[FILL]' },
      { question: 'Can physiotherapy cure sciatica permanently?', answer: '[FILL]' },
      { question: 'When should I see a doctor for sciatica?', answer: '[FILL]' },
    ],
  },

  // ── POST 8 ──────────────────────────────────────────────────────────────
  {
    title: 'Post-Surgery Rehabilitation: What to Expect',
    slug: 'post-surgery-rehabilitation-what-to-expect',
    excerpt:
      'Surgery is only half the journey. A structured physiotherapy rehabilitation programme determines how well and how quickly you recover.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 8,
    ranchi_reference: false,
    categories: ['Sports & Rehabilitation'],
    tags: ['post-surgery', 'rehabilitation', 'knee pain', 'shoulder'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Patient doing post-surgical rehabilitation exercises with physiotherapist, clinical gym setting',
    stock_search_keywords: ['post surgery physiotherapy', 'surgical rehabilitation', 'post-op physiotherapy'],
    content: [
      h2('Why Post-Surgical Rehabilitation Matters'),
      p('[OUTLINE: 150 words — tissue healing, muscle atrophy, scar tissue management, return to function]'),
      h2('Common Surgeries That Require Physiotherapy'),
      ul('[LIST ITEM: total knee replacement]', '[LIST ITEM: ACL reconstruction]', '[LIST ITEM: rotator cuff repair]', '[LIST ITEM: total hip replacement]', '[LIST ITEM: spinal surgery (laminectomy, fusion)]'),
      h2('Timeline: What Happens in Each Phase'),
      h3('Phase 1: Acute (0–2 weeks post-op)'),
      p('[OUTLINE: 150 words — pain/swelling management, protected weight-bearing, range of motion initiation]'),
      h3('Phase 2: Subacute (2–6 weeks)'),
      p('[OUTLINE: 150 words — progressive strengthening, gait training, scar tissue management]'),
      h3('Phase 3: Functional Rehabilitation (6–12 weeks)'),
      p('[OUTLINE: 150 words — functional movement patterns, sport/work-specific exercises]'),
      h2('What to Ask Your Surgeon Before Physiotherapy Starts'),
      p('[OUTLINE: 150 words — weight-bearing status, precautions, ROM restrictions]'),
      h2('How to Get the Most from Your Post-Surgical Rehab'),
      p('[OUTLINE: 150 words — compliance with home programme, pacing, nutrition]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'When should physiotherapy start after surgery?', answer: '[FILL]' },
      { question: 'How many sessions of physiotherapy do I need after surgery?', answer: '[FILL]' },
      { question: 'Can I do physiotherapy at home after surgery?', answer: '[FILL]' },
      { question: 'What happens if I skip post-surgical physiotherapy?', answer: '[FILL]' },
      { question: 'Will physiotherapy be painful after surgery?', answer: '[FILL]' },
    ],
  },

  // ── POST 9 ──────────────────────────────────────────────────────────────
  {
    title: 'Stroke Rehabilitation with Physiotherapy',
    slug: 'stroke-rehabilitation-physiotherapy',
    excerpt:
      'Early and intensive physiotherapy is the single most effective intervention for stroke recovery. Learn how neuroplasticity and task-specific training restore function.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 8,
    ranchi_reference: false,
    categories: ['Neuro & Paediatric'],
    tags: ['stroke', 'neurological', 'rehabilitation', 'balance'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist assisting stroke patient with walking rehabilitation, hospital corridor setting',
    stock_search_keywords: ['stroke physiotherapy', 'stroke rehabilitation exercises', 'neurological physiotherapy'],
    content: [
      h2('How Stroke Affects Movement'),
      p('[OUTLINE: 150 words — hemiplegia, spasticity, foot drop, balance impairment, dysphagia]'),
      h2('The Role of Neuroplasticity in Recovery'),
      p('[OUTLINE: 200 words — brain rewiring, critical window (first 3 months), repetitive task practice]'),
      h2('Physiotherapy Assessment After Stroke'),
      p('[OUTLINE: 150 words — Fugl-Meyer, Berg Balance Scale, functional mobility assessment]'),
      h2('Physiotherapy Interventions for Stroke'),
      p('[OUTLINE: 200 words — task-specific training, constraint-induced movement therapy, mirror therapy, gait re-education]'),
      h2('Managing Spasticity and Contractures'),
      p('[OUTLINE: 150 words — stretching, splinting, positioning, botulinum toxin adjunct]'),
      h2('Setting Realistic Recovery Goals'),
      p('[OUTLINE: 150 words — SMART goals, factors affecting prognosis, family involvement]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA to RNB Clinic neuro team]'),
    ],
    faqs: [
      { question: 'How long does stroke rehabilitation take?', answer: '[FILL]' },
      { question: 'Can you fully recover from a stroke?', answer: '[FILL]' },
      { question: 'How many physiotherapy sessions are needed for stroke?', answer: '[FILL]' },
      { question: 'What exercises help stroke recovery at home?', answer: '[FILL]' },
      { question: 'When should stroke physiotherapy start?', answer: '[FILL]' },
    ],
  },

  // ── POST 10 ─────────────────────────────────────────────────────────────
  {
    title: 'Cerebral Palsy and Paediatric Physiotherapy',
    slug: 'cerebral-palsy-paediatric-physiotherapy',
    excerpt:
      'Early physiotherapy intervention for children with cerebral palsy can dramatically improve mobility, function, and quality of life. Here is what families need to know.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Neuro & Paediatric'],
    tags: ['cerebral palsy', 'paediatric', 'neurological', 'rehabilitation'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Paediatric physiotherapist working with child on padded mat, bright colourful therapy room',
    stock_search_keywords: ['cerebral palsy physiotherapy', 'paediatric physiotherapy India', 'CP rehabilitation'],
    content: [
      h2('What Is Cerebral Palsy?'),
      p('[OUTLINE: 150 words — definition, types (spastic, athetoid, ataxic), causes, prevalence]'),
      h2('Why Physiotherapy Is Critical for Children with CP'),
      p('[OUTLINE: 150 words — neuroplasticity in childhood, prevent contractures, functional independence goals]'),
      h2('Physiotherapy Goals for Children with Cerebral Palsy'),
      ul('[LIST ITEM: improving muscle tone and strength]', '[LIST ITEM: developing gross motor milestones]', '[LIST ITEM: preventing secondary musculoskeletal complications]', '[LIST ITEM: enhancing balance and coordination]', '[LIST ITEM: supporting participation in school and play]'),
      h2('Physiotherapy Techniques for Cerebral Palsy'),
      p('[OUTLINE: 200 words — NDT/Bobath, task-oriented training, hippotherapy adjunct, orthoses]'),
      h2('Home Exercise Programme for Parents'),
      p('[OUTLINE: 200 words — stretching routines, positioning, handling techniques, daily activities as therapy]'),
      h2('When to Start Physiotherapy for a Child with CP'),
      p('[OUTLINE: 150 words — early diagnosis, early intervention evidence, NICU physiotherapy]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — compassionate CTA to paediatric team at RNB Clinic]'),
    ],
    faqs: [
      { question: 'At what age should physiotherapy start for cerebral palsy?', answer: '[FILL]' },
      { question: 'Can physiotherapy cure cerebral palsy?', answer: '[FILL]' },
      { question: 'How often should a child with CP have physiotherapy?', answer: '[FILL]' },
      { question: 'What is the Bobath technique for cerebral palsy?', answer: '[FILL]' },
      { question: 'Will my child with cerebral palsy be able to walk?', answer: '[FILL]' },
    ],
  },

  // ── POST 11 ─────────────────────────────────────────────────────────────
  {
    title: 'Physiotherapy for Elderly: Falls Prevention & Mobility',
    slug: 'physiotherapy-elderly-falls-prevention-mobility',
    excerpt:
      'Falls are the leading cause of injury in adults over 65. A structured physiotherapy programme can reduce fall risk by up to 30%. Here is how it works.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Health & Lifestyle'],
    tags: ['elderly', 'balance', 'rehabilitation', 'exercise therapy'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist assisting elderly patient with balance exercises, parallel bars, bright clinic',
    stock_search_keywords: ['elderly physiotherapy', 'falls prevention exercises', 'geriatric physiotherapy India'],
    content: [
      h2('Why Do Elderly People Fall?'),
      p('[OUTLINE: 150 words — sarcopenia, balance decline, polypharmacy, vision, environmental hazards]'),
      h2('The Consequences of Falls in Older Adults'),
      p('[OUTLINE: 150 words — hip fracture, fear of falling, loss of independence, mortality statistics]'),
      h2('Falls Risk Assessment'),
      p('[OUTLINE: 150 words — Berg Balance Scale, Timed Up and Go test, gait assessment]'),
      h2('Physiotherapy Interventions for Falls Prevention'),
      p('[OUTLINE: 200 words — balance training, strength training, Tai Chi, walking aids prescription]'),
      h3('Balance Exercise Examples'),
      ul('[LIST ITEM: single leg stance progression]', '[LIST ITEM: tandem stance / walking]', '[LIST ITEM: sit-to-stand practice]', '[LIST ITEM: stepping over obstacles]', '[LIST ITEM: dual-task training]'),
      h2('Home Safety and Environmental Modifications'),
      p('[OUTLINE: 150 words — grab rails, bathroom safety, trip hazard removal, lighting]'),
      h2('Keeping Active Safely'),
      p('[OUTLINE: 150 words — walking groups, community exercise, aquatic therapy]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'How many falls does it take for an elderly person to be at high risk?', answer: '[FILL]' },
      { question: 'What exercises reduce fall risk in the elderly?', answer: '[FILL]' },
      { question: 'Is physiotherapy safe for very elderly patients (85+)?', answer: '[FILL]' },
      { question: 'Can physiotherapy help with dizziness and balance problems?', answer: '[FILL]' },
      { question: 'How do I know if my elderly parent needs a walking frame?', answer: '[FILL]' },
    ],
  },

  // ── POST 12 ─────────────────────────────────────────────────────────────
  {
    title: 'Posture Correction Exercises You Can Do at Home',
    slug: 'posture-correction-exercises-at-home',
    excerpt:
      'Poor posture is a silent epidemic in our desk-bound world. These physiotherapist-approved exercises can reset your posture in 15 minutes a day.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Health & Lifestyle'],
    tags: ['posture', 'back pain', 'neck pain', 'exercise therapy'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Person performing posture correction exercise against wall, home setting, clear posture demonstration',
    stock_search_keywords: ['posture correction exercises', 'fix bad posture', 'desk posture physiotherapy'],
    content: [
      h2('What Causes Poor Posture?'),
      p('[OUTLINE: 150 words — prolonged sitting, device use, weak postural muscles, muscle imbalances]'),
      h2('Signs You Have Poor Posture'),
      ul('[LIST ITEM: forward head posture]', '[LIST ITEM: rounded shoulders]', '[LIST ITEM: anterior pelvic tilt]', '[LIST ITEM: flat back or kyphosis]', '[LIST ITEM: uneven hip height]'),
      h2('Why Poor Posture Causes Pain'),
      p('[OUTLINE: 150 words — compressive loads, muscle fatigue, nerve irritation, headache mechanism]'),
      h2('Physiotherapist-Approved Exercises for Better Posture'),
      h3('Upper Body Posture Exercises'),
      ul('[LIST ITEM: chin tucks — 10 × 10-second hold]', '[LIST ITEM: thoracic extension over foam roller]', '[LIST ITEM: shoulder blade retractions]', '[LIST ITEM: chest opening stretch (doorway stretch)]', '[LIST ITEM: wall angels]'),
      h3('Core and Lower Body Posture Exercises'),
      ul('[LIST ITEM: dead bug exercise]', '[LIST ITEM: glute bridges]', '[LIST ITEM: hip flexor stretches]', '[LIST ITEM: clamshell exercise for lateral hip]', '[LIST ITEM: prone cobra for upper back extension]'),
      h2('Ergonomic Setup for Desk Workers'),
      p('[OUTLINE: 200 words — monitor height, chair height, keyboard position, standing desk use]'),
      h2('Building a Daily Posture Routine'),
      p('[OUTLINE: 150 words — 15-minute daily programme, habit stacking, reminders]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'How long does it take to correct posture?', answer: '[FILL]' },
      { question: 'Can posture braces fix bad posture?', answer: '[FILL]' },
      { question: 'What is the best posture for sitting at a desk?', answer: '[FILL]' },
      { question: 'Is poor posture reversible?', answer: '[FILL]' },
      { question: 'Do I need to see a physiotherapist for posture problems?', answer: '[FILL]' },
    ],
  },

  // ── POST 13 ─────────────────────────────────────────────────────────────
  {
    title: 'Plantar Fasciitis: Foot Pain Treatment Guide',
    slug: 'plantar-fasciitis-foot-pain-treatment-guide',
    excerpt:
      'That stabbing heel pain when you take your first morning steps is often plantar fasciitis. Learn why it happens and how physiotherapy resolves it.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Health & Lifestyle'],
    tags: ['plantar fasciitis', 'foot pain', 'sports injury', 'exercise therapy'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist performing ultrasound treatment on patient heel, clinical treatment room',
    stock_search_keywords: ['plantar fasciitis treatment', 'heel pain physiotherapy', 'foot pain exercises'],
    content: [
      h2('What Is Plantar Fasciitis?'),
      p('[OUTLINE: 150 words — anatomy of plantar fascia, degenerative vs inflammatory debate, common presentation]'),
      h2('Causes and Risk Factors'),
      p('[OUTLINE: 150 words — prolonged standing, sudden increase in activity, tight calves, flat/high arch foot type]'),
      h2('Physiotherapy Assessment for Heel Pain'),
      p('[OUTLINE: 150 words — foot posture assessment, gait analysis, calf flexibility testing, differential diagnosis]'),
      h2('Treatment Options at The Clinic'),
      p('[OUTLINE: 200 words — ESWT, dry needling, ultrasound therapy, taping, orthoses prescription]'),
      h2('Exercise Programme for Plantar Fasciitis'),
      ul('[LIST ITEM: plantar fascia self-stretch (towel method)]', '[LIST ITEM: calf stretches — gastrocnemius and soleus]', '[LIST ITEM: eccentric calf loading (Alfredson protocol modified)]', '[LIST ITEM: intrinsic foot strengthening exercises]', '[LIST ITEM: toe towel scrunches]'),
      h2('How Long Does Plantar Fasciitis Last?'),
      p('[OUTLINE: 150 words — prognosis, typical timeline with physio, without treatment outcomes]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'Will plantar fasciitis go away on its own?', answer: '[FILL]' },
      { question: 'What is the fastest way to cure plantar fasciitis?', answer: '[FILL]' },
      { question: 'Should I walk or rest with plantar fasciitis?', answer: '[FILL]' },
      { question: 'What shoes are best for plantar fasciitis?', answer: '[FILL]' },
      { question: 'Does stretching help plantar fasciitis?', answer: '[FILL]' },
    ],
  },

  // ── POST 14 ─────────────────────────────────────────────────────────────
  {
    title: 'Carpal Tunnel Syndrome: Physiotherapy Approach',
    slug: 'carpal-tunnel-syndrome-physiotherapy-approach',
    excerpt:
      'Carpal tunnel syndrome causes numbness, tingling, and weakness in the hand. Physiotherapy can be highly effective — often avoiding the need for surgery.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Health & Lifestyle'],
    tags: ['carpal tunnel', 'manual therapy', 'electrotherapy', 'exercise therapy'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist applying splint to patient wrist, treatment of carpal tunnel, clinical setting',
    stock_search_keywords: ['carpal tunnel physiotherapy', 'carpal tunnel treatment', 'wrist nerve pain'],
    content: [
      h2('What Is Carpal Tunnel Syndrome?'),
      p('[OUTLINE: 150 words — anatomy of carpal tunnel, median nerve compression, symptoms]'),
      h2('Causes and Risk Factors'),
      p('[OUTLINE: 150 words — repetitive hand use, fluid retention, diabetes, rheumatoid arthritis, pregnancy]'),
      h2('Diagnosis: How Physiotherapists Assess CTS'),
      p('[OUTLINE: 150 words — Phalen test, Tinel sign, two-point discrimination, Semmes-Weinstein]'),
      h2('Conservative Physiotherapy Treatment'),
      p('[OUTLINE: 200 words — nocturnal splinting, neural mobilisation, wrist strengthening, ergonomic advice]'),
      h2('Electrotherapy for Carpal Tunnel'),
      p('[OUTLINE: 150 words — ultrasound evidence, TENS for symptom relief, laser therapy adjunct]'),
      h2('Surgery vs Physiotherapy: What Does the Evidence Say?'),
      p('[OUTLINE: 200 words — mild/moderate responds well to conservative care, surgery for severe]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'Can carpal tunnel syndrome be treated without surgery?', answer: '[FILL]' },
      { question: 'Is it OK to exercise with carpal tunnel syndrome?', answer: '[FILL]' },
      { question: 'How long does carpal tunnel physiotherapy take?', answer: '[FILL]' },
      { question: 'Does typing make carpal tunnel worse?', answer: '[FILL]' },
      { question: 'Should I wear a wrist splint all day for carpal tunnel?', answer: '[FILL]' },
    ],
  },

  // ── POST 15 ─────────────────────────────────────────────────────────────
  {
    title: 'Tennis Elbow Treatment Without Cortisone',
    slug: 'tennis-elbow-treatment-without-cortisone',
    excerpt:
      'Cortisone injections offer short-term relief for tennis elbow but high recurrence rates. Discover why physiotherapy and eccentric loading produce better lasting outcomes.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Sports & Rehabilitation'],
    tags: ['tennis elbow', 'manual therapy', 'exercise therapy', 'rehabilitation'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist applying dry needling to lateral elbow region, tennis elbow treatment, clinical setting',
    stock_search_keywords: ['tennis elbow treatment', 'lateral epicondylitis physiotherapy', 'elbow pain treatment'],
    content: [
      h2('What Is Tennis Elbow?'),
      p('[OUTLINE: 150 words — lateral epicondylitis vs epicondylosis, common extensor tendon origin, angiofibroblastic change]'),
      h2('Why Cortisone Injections Are Not the Answer Long-Term'),
      p('[OUTLINE: 200 words — RCT evidence, 6-week improvement but 12-month worse outcomes vs physio, tendon weakening]'),
      h2('Physiotherapy Assessment'),
      p('[OUTLINE: 150 words — grip strength, Cozen test, Mill\'s test, cervical screen]'),
      h2('Eccentric and Isometric Loading for Tendon Rehab'),
      p('[OUTLINE: 200 words — Tyler twist protocol, isometric holds for pain relief, progressive loading timeline]'),
      h2('Manual Therapy and Dry Needling'),
      p('[OUTLINE: 150 words — lateral epicondyle mobilisation with movement, dry needling into extensor digitorum communis]'),
      h2('Bracing and Activity Modification'),
      p('[OUTLINE: 150 words — counterforce brace mechanism, activity analysis, grip ergonomics]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'How long does tennis elbow take to heal?', answer: '[FILL]' },
      { question: 'Should I stop playing sport with tennis elbow?', answer: '[FILL]' },
      { question: 'Does a tennis elbow brace actually help?', answer: '[FILL]' },
      { question: 'What is the Tyler twist exercise for tennis elbow?', answer: '[FILL]' },
      { question: 'Can tennis elbow come back after physiotherapy?', answer: '[FILL]' },
    ],
  },

  // ── POST 16 ─────────────────────────────────────────────────────────────
  {
    title: 'Dry Needling vs Acupuncture: Key Differences Explained',
    slug: 'dry-needling-vs-acupuncture-key-differences',
    excerpt:
      'Dry needling and acupuncture both use thin needles but are completely different in theory and practice. Understand the key differences.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 6,
    ranchi_reference: false,
    categories: ['Health & Lifestyle'],
    tags: ['dry needling', 'acupuncture', 'manual therapy', 'physiotherapy'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Close-up of dry needling into muscle trigger point, clinical precision, blue gloves',
    stock_search_keywords: ['dry needling vs acupuncture', 'physiotherapy needling', 'trigger point dry needling'],
    content: [
      h2('What Is Dry Needling?'),
      p('[OUTLINE: 150 words — trigger point therapy, Western physiology basis, physiotherapist training]'),
      h2('What Is Acupuncture?'),
      p('[OUTLINE: 150 words — TCM meridian theory, Qi, 2000-year history, practitioner types]'),
      h2('Key Differences'),
      h3('Theoretical Basis'),
      p('[OUTLINE: compare anatomy/neurophysiology vs meridian/Qi systems]'),
      h3('Needle Placement'),
      p('[OUTLINE: trigger points vs acupoints, palpation vs meridian maps]'),
      h3('Practitioners and Training'),
      p('[OUTLINE: physiotherapist post-grad certification vs TCM qualification]'),
      h3('Evidence Base'),
      p('[OUTLINE: growing RCT evidence for dry needling vs mixed evidence for acupuncture]'),
      h2('Which Should You Choose?'),
      p('[OUTLINE: 150 words — condition-specific guidance, combined approach option]'),
      h2('What to Expect During a Dry Needling Session'),
      p('[OUTLINE: 150 words — local twitch response, post-session soreness, duration]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'Is dry needling painful?', answer: '[FILL]' },
      { question: 'How many dry needling sessions do I need?', answer: '[FILL]' },
      { question: 'Is dry needling safe?', answer: '[FILL]' },
      { question: 'Can dry needling help back pain?', answer: '[FILL]' },
      { question: 'Do physiotherapists in India practice dry needling?', answer: '[FILL]' },
    ],
  },

  // ── POST 17 ─────────────────────────────────────────────────────────────
  {
    title: 'TENS Therapy Explained: Benefits and Uses',
    slug: 'tens-therapy-explained-benefits-uses',
    excerpt:
      'Transcutaneous electrical nerve stimulation (TENS) is a widely used pain relief tool in physiotherapy. Discover how it works and who benefits most.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 6,
    ranchi_reference: false,
    categories: ['Health & Lifestyle'],
    tags: ['tens therapy', 'electrotherapy', 'physiotherapy', 'back pain'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'TENS electrodes applied to patient lower back, electrotherapy machine visible, clinical treatment',
    stock_search_keywords: ['TENS therapy physiotherapy', 'TENS machine benefits', 'electrotherapy pain relief'],
    content: [
      h2('What Is TENS Therapy?'),
      p('[OUTLINE: 150 words — transcutaneous electrical nerve stimulation, electrode pads, mechanism of action]'),
      h2('How TENS Works to Relieve Pain'),
      p('[OUTLINE: 200 words — gate control theory, endorphin release, high vs low frequency TENS]'),
      h2('Conditions TENS Is Used For'),
      ul('[LIST ITEM: chronic back and neck pain]', '[LIST ITEM: osteoarthritis]', '[LIST ITEM: post-surgical pain]', '[LIST ITEM: fibromyalgia]', '[LIST ITEM: labour pain management]'),
      h2('TENS at The Clinic vs Home TENS Machines'),
      p('[OUTLINE: 150 words — clinical grade devices, home use guidance, electrode placement charts]'),
      h2('How to Use a Home TENS Machine Safely'),
      p('[OUTLINE: 200 words — electrode placement rules, contraindications: pacemaker, pregnancy, skin sensitivity]'),
      h2('Limitations of TENS: What It Cannot Do'),
      p('[OUTLINE: 150 words — not curative, analgesic effect, still need addressing root cause]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'Is TENS therapy safe to use every day?', answer: '[FILL]' },
      { question: 'Where should you NOT put TENS pads?', answer: '[FILL]' },
      { question: 'How long should a TENS session last?', answer: '[FILL]' },
      { question: 'Can TENS therapy make pain worse?', answer: '[FILL]' },
      { question: 'Is TENS therapy good for nerve pain?', answer: '[FILL]' },
    ],
  },

  // ── POST 18 ─────────────────────────────────────────────────────────────
  {
    title: 'Ultrasound Therapy in Physiotherapy: What You Need to Know',
    slug: 'ultrasound-therapy-physiotherapy-what-to-know',
    excerpt:
      'Therapeutic ultrasound is one of the most commonly used electrotherapy tools in physiotherapy clinics. Here is how it works and when it is most effective.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 6,
    ranchi_reference: false,
    categories: ['Health & Lifestyle'],
    tags: ['ultrasound therapy', 'electrotherapy', 'physiotherapy', 'rehabilitation'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist applying therapeutic ultrasound probe to patient shoulder, clinical treatment',
    stock_search_keywords: ['therapeutic ultrasound physiotherapy', 'ultrasound therapy benefits', 'electrotherapy treatment'],
    content: [
      h2('What Is Therapeutic Ultrasound?'),
      p('[OUTLINE: 150 words — sound waves at 1–3 MHz, transducer probe, coupling gel, thermal vs non-thermal effects]'),
      h2('Thermal Effects: Deep Tissue Heating'),
      p('[OUTLINE: 150 words — continuous mode, heating deeper than hot packs, tissue extensibility improvement]'),
      h2('Non-Thermal Effects: Cavitation and Acoustic Streaming'),
      p('[OUTLINE: 200 words — pulsed mode, micro-bubble formation, cell membrane permeability, wound healing acceleration]'),
      h2('Conditions Treated with Therapeutic Ultrasound'),
      ul('[LIST ITEM: shoulder tendinopathy and bursitis]', '[LIST ITEM: plantar fasciitis]', '[LIST ITEM: frozen shoulder]', '[LIST ITEM: carpal tunnel syndrome]', '[LIST ITEM: calcific tendinitis]'),
      h2('Ultrasound vs TENS: Which Is Better for My Condition?'),
      p('[OUTLINE: 150 words — comparison, different mechanisms, often used together]'),
      h2('Safety and Contraindications'),
      p('[OUTLINE: 200 words — avoid over growth plates, over metal implants, near eyes, thrombosis areas, malignancy]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'Does ultrasound therapy actually work?', answer: '[FILL]' },
      { question: 'Is ultrasound therapy safe during pregnancy?', answer: '[FILL]' },
      { question: 'How many ultrasound therapy sessions do I need?', answer: '[FILL]' },
      { question: 'Can ultrasound therapy dissolve calcium deposits?', answer: '[FILL]' },
      { question: 'Is ultrasound therapy the same as a diagnostic scan?', answer: '[FILL]' },
    ],
  },

  // ── POST 19 ─────────────────────────────────────────────────────────────
  {
    title: 'Core Strengthening for Low Back Pain: The Complete Guide',
    slug: 'core-strengthening-low-back-pain-guide',
    excerpt:
      'Core strengthening is the cornerstone of back pain rehabilitation. Learn which muscles matter, why common advice is outdated, and which exercises actually work.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 8,
    ranchi_reference: false,
    categories: ['Back & Spine'],
    tags: ['core strengthening', 'back pain', 'spine', 'exercise therapy'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Person performing bird-dog exercise on mat, physiotherapy exercise, core stability training',
    stock_search_keywords: ['core exercises for back pain', 'core strengthening physiotherapy', 'lower back strengthening'],
    content: [
      h2('The Core: More Than Just Six-Pack Abs'),
      p('[OUTLINE: 150 words — transversus abdominis, multifidus, pelvic floor, diaphragm — the "deep" core]'),
      h2('Why a Weak Core Causes Back Pain'),
      p('[OUTLINE: 200 words — motor control deficits, delayed muscle activation, spinal instability model]'),
      h2('Outdated Core Advice (And What to Do Instead)'),
      p('[OUTLINE: 200 words — sit-ups cause pain, Biering-Sorensen extension holds — better options]'),
      h2('Phase 1: Core Activation Exercises (Beginner)'),
      ul('[LIST ITEM: abdominal hollowing (ADIM)]', '[LIST ITEM: diaphragmatic breathing]', '[LIST ITEM: pelvic tilts]', '[LIST ITEM: heel slides in crook lying]', '[LIST ITEM: supine marching]'),
      h2('Phase 2: Core Stability Exercises (Intermediate)'),
      ul('[LIST ITEM: bird-dog]', '[LIST ITEM: dead bug]', '[LIST ITEM: modified side plank (knee bent)]', '[LIST ITEM: glute bridge]', '[LIST ITEM: clamshell with resistance band]'),
      h2('Phase 3: Functional Core Loading (Advanced)'),
      ul('[LIST ITEM: pallof press]', '[LIST ITEM: Turkish get-up (adapted)]', '[LIST ITEM: cable woodchop]', '[LIST ITEM: single-leg deadlift]', '[LIST ITEM: landmine rotation]'),
      h2('How to Progress Your Core Programme Safely'),
      p('[OUTLINE: 150 words — principles of progression, pain monitoring, when to advance]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'Are sit-ups bad for back pain?', answer: '[FILL]' },
      { question: 'How often should I do core exercises for back pain?', answer: '[FILL]' },
      { question: 'What is the single best core exercise for back pain?', answer: '[FILL]' },
      { question: 'Should I do core exercises during a back pain flare-up?', answer: '[FILL]' },
      { question: 'How long before core exercises relieve back pain?', answer: '[FILL]' },
    ],
  },

  // ── POST 20 ─────────────────────────────────────────────────────────────
  {
    title: 'Physiotherapy During Pregnancy: Safe Exercises and Benefits',
    slug: 'physiotherapy-during-pregnancy-safe-exercises',
    excerpt:
      'Pregnancy brings significant physical changes that often cause back pain, pelvic girdle pain, and postural strain. Physiotherapy keeps you comfortable and prepared for labour.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Health & Lifestyle'],
    tags: ['pregnancy', "women's health", 'back pain', 'exercise therapy'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Pregnant woman doing supported stretching with physiotherapist, bright clinical setting',
    stock_search_keywords: ['physiotherapy during pregnancy', 'pregnancy back pain treatment', 'antenatal physiotherapy'],
    content: [
      h2('Physical Changes During Pregnancy That Cause Pain'),
      p('[OUTLINE: 150 words — relaxin hormone, postural changes, centre of gravity shift, round ligament, uterus growth]'),
      h2('Common Conditions Physiotherapy Treats During Pregnancy'),
      ul('[LIST ITEM: lower back pain and sacroiliac joint pain]', '[LIST ITEM: pelvic girdle pain (PGP)]', '[LIST ITEM: carpal tunnel syndrome]', '[LIST ITEM: diastasis recti]', '[LIST ITEM: leg cramps and calf tightness]'),
      h2('Is Physiotherapy Safe During Pregnancy?'),
      p('[OUTLINE: 200 words — specific safety guidelines, manual therapy considerations, trimester-specific advice]'),
      h2('Safe Exercises for Each Trimester'),
      h3('First Trimester Exercises'),
      p('[OUTLINE: 100 words — gentle mobility, diaphragmatic breathing, pelvic floor activation]'),
      h3('Second Trimester Exercises'),
      p('[OUTLINE: 100 words — prenatal yoga elements, modified strength training, water therapy]'),
      h3('Third Trimester Exercises'),
      p('[OUTLINE: 100 words — supported positions, birth preparation breathing, pelvic floor]'),
      h2('Physiotherapy for Postnatal Recovery'),
      p('[OUTLINE: 150 words — diastasis recti rehabilitation, return to exercise, pelvic floor recovery]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'Is it safe to see a physiotherapist while pregnant?', answer: '[FILL]' },
      { question: 'When should I see a physiotherapist during pregnancy?', answer: '[FILL]' },
      { question: 'What exercises are safe in all trimesters?', answer: '[FILL]' },
      { question: 'Can physiotherapy help with pelvic girdle pain in pregnancy?', answer: '[FILL]' },
      { question: 'How do I heal diastasis recti after childbirth?', answer: '[FILL]' },
    ],
  },

  // ── POST 21 ─────────────────────────────────────────────────────────────
  {
    title: 'Best Physiotherapy Clinic in Ranchi: What to Look For',
    slug: 'best-physiotherapy-clinic-ranchi-what-to-look-for',
    excerpt:
      'Choosing the right physiotherapy clinic in Ranchi can make all the difference in your recovery. Here is what sets a world-class clinic apart.',
    seo_title: '// FILL: ~60 chars — e.g. "Best Physiotherapy Clinic in Ranchi | The RNB Clinic"',
    seo_description: '// FILL: ~155 chars — include "physiotherapy clinic Ranchi", "RNB Clinic"',
    reading_time: 7,
    ranchi_reference: true,
    categories: ['Local Ranchi Health'],
    tags: ['ranchi', 'physiotherapy', 'physiotherapy basics'],
    featured_image_alt: '// FILL: descriptive alt text — mention Ranchi',
    featured_image_suggestion: 'Modern physiotherapy clinic reception, welcoming design, The RNB Clinic branding, Ranchi',
    stock_search_keywords: ['physiotherapy clinic Ranchi', 'best physio Ranchi', 'RNB Clinic Ranchi'],
    content: [
      h2('Why Choosing the Right Physiotherapy Clinic Matters'),
      p('[OUTLINE: 150 words — impact on outcomes, cost of poor treatment, importance of evidence-based care]'),
      h2('7 Qualities to Look for in a Physiotherapy Clinic in Ranchi'),
      ul(
        '[LIST ITEM: qualified and registered physiotherapists (BPT/MPT)]',
        '[LIST ITEM: evidence-based treatment protocols]',
        '[LIST ITEM: individualised treatment plans — not one-size-fits-all]',
        '[LIST ITEM: modern equipment and clean clinical environment]',
        '[LIST ITEM: clear communication and patient education]',
        '[LIST ITEM: transparent pricing and no unnecessary sessions]',
        '[LIST ITEM: positive patient reviews and outcomes]'
      ),
      h2('What to Ask Before Booking'),
      p('[OUTLINE: 200 words — questions about therapist qualifications, treatment approach, expected timeline]'),
      h2('Red Flags: Warning Signs of a Poor Clinic'),
      p('[OUTLINE: 150 words — passive treatment only, no assessment, no home programme, vague treatment plans]'),
      h2('About The RNB Clinic, Ranchi'),
      p('[OUTLINE: 200 words — team qualifications, clinic values, services, location in Ranchi, patient outcomes focus]'),
      h2('How to Book Your First Appointment'),
      p('[OUTLINE: 100 words — booking process, what to bring, parking/location]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — strong local CTA]'),
    ],
    faqs: [
      { question: 'What qualifications should a physiotherapist in India have?', answer: '[FILL]' },
      { question: 'How much does physiotherapy cost in Ranchi?', answer: '[FILL]' },
      { question: 'Does The RNB Clinic accept walk-in appointments?', answer: '[FILL]' },
      { question: 'What is the best physiotherapy clinic in Ranchi for back pain?', answer: '[FILL]' },
      { question: 'How is physiotherapy different from a general massage?', answer: '[FILL]' },
    ],
  },

  // ── POST 22 ─────────────────────────────────────────────────────────────
  {
    title: 'Sports Physiotherapy in Ranchi: Helping Athletes Recover Faster',
    slug: 'sports-physiotherapy-ranchi-athlete-recovery',
    excerpt:
      'Ranchi is home to a growing sporting culture. The RNB Clinic provides specialised sports physiotherapy to keep local athletes performing at their best.',
    seo_title: '// FILL: ~60 chars — e.g. "Sports Physiotherapy Ranchi | Athlete Recovery | RNB Clinic"',
    seo_description: '// FILL: ~155 chars — include "sports physiotherapy Ranchi"',
    reading_time: 7,
    ranchi_reference: true,
    categories: ['Local Ranchi Health'],
    tags: ['ranchi', 'sports injury', 'rehabilitation', 'physiotherapy'],
    featured_image_alt: '// FILL: descriptive alt text — mention Ranchi sports',
    featured_image_suggestion: 'Sports physiotherapist treating athlete knee at clinic in Ranchi, sports setting, blue/white',
    stock_search_keywords: ['sports physiotherapy Ranchi', 'sports injury treatment Ranchi', 'athlete physio Jharkhand'],
    content: [
      h2("Ranchi's Growing Sporting Culture"),
      p('[OUTLINE: 150 words — cricket, football, hockey, athletics in Ranchi and Jharkhand; need for specialist sports physio]'),
      h2('What Is Sports Physiotherapy?'),
      p('[OUTLINE: 150 words — subspecialty, injury prevention + treatment + performance, sports-specific training]'),
      h2('Common Sports Injuries Treated at RNB Clinic'),
      ul('[LIST ITEM: ACL and ligament tears]', '[LIST ITEM: muscle strains (hamstring, groin, calf)]', '[LIST ITEM: shoulder and rotator cuff injuries]', '[LIST ITEM: ankle sprains and instability]', '[LIST ITEM: stress fractures and overuse injuries]'),
      h2('Our Sports Physiotherapy Approach'),
      p('[OUTLINE: 200 words — biomechanical assessment, injury rehab, return-to-sport testing, injury prevention programmes]'),
      h2('Performance Optimisation: Beyond Injury Recovery'),
      p('[OUTLINE: 150 words — movement screening, strength asymmetry correction, conditioning]'),
      h2('Injury Prevention Programmes for Ranchi Athletes'),
      p('[OUTLINE: 200 words — FIFA 11+, pre-season screening, team-based programmes, school athlete programmes]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — strong local CTA to book at RNB Clinic Ranchi]'),
    ],
    faqs: [
      { question: 'Do I need a sports physiotherapist or a regular physiotherapist?', answer: '[FILL]' },
      { question: 'Can physiotherapy improve athletic performance?', answer: '[FILL]' },
      { question: 'How quickly can a physiotherapist get me back to playing sport?', answer: '[FILL]' },
      { question: 'Does The RNB Clinic work with schools and sports teams in Ranchi?', answer: '[FILL]' },
      { question: 'What is the FIFA 11+ warm-up programme?', answer: '[FILL]' },
    ],
  },

  // ── POST 23 ─────────────────────────────────────────────────────────────
  {
    title: 'Knee Replacement Recovery: The Physiotherapy Protocol',
    slug: 'knee-replacement-recovery-physiotherapy-protocol',
    excerpt:
      'Total knee replacement is one of the most successful orthopaedic surgeries — but the outcome depends heavily on your physiotherapy programme.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 8,
    ranchi_reference: false,
    categories: ['Sports & Rehabilitation'],
    tags: ['post-surgery', 'knee pain', 'rehabilitation', 'joints'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist assisting patient with walking frame after knee replacement, hospital ward',
    stock_search_keywords: ['knee replacement physiotherapy', 'total knee replacement recovery', 'TKR rehabilitation'],
    content: [
      h2('Why Physiotherapy Determines Your Knee Replacement Outcome'),
      p('[OUTLINE: 150 words — muscle atrophy prevention, ROM recovery, gait normalisation]'),
      h2('Before Surgery: Prehabilitation'),
      p('[OUTLINE: 200 words — quad strengthening, cardiovascular fitness, walking aids training, expected outcome education]'),
      h2('Week 1–2: Hospital and Early Home Phase'),
      p('[OUTLINE: 200 words — ankle pumps, quad sets, knee extension/flexion, mobility with frame, pain monitoring]'),
      h2('Week 2–6: Progressive Rehabilitation'),
      p('[OUTLINE: 200 words — stationary cycling, stair training, progressive weight-bearing, scar tissue management]'),
      h2('Month 2–3: Functional Rehabilitation'),
      p('[OUTLINE: 150 words — return to normal walking, balance training, strengthening progression]'),
      h2('Month 3–6: Return to Full Function'),
      p('[OUTLINE: 150 words — sports/activity return, driving, long-distance walking goals]'),
      h2('Red Flags: When to Contact Your Surgeon'),
      p('[OUTLINE: 100 words — fever, severe swelling, wound opening, sudden severe pain]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'How soon after knee replacement should physiotherapy start?', answer: '[FILL]' },
      { question: 'How long until I can walk normally after knee replacement?', answer: '[FILL]' },
      { question: 'What exercises should I avoid after knee replacement?', answer: '[FILL]' },
      { question: 'How do I manage pain during physiotherapy after knee replacement?', answer: '[FILL]' },
      { question: 'What is a normal range of motion goal after knee replacement?', answer: '[FILL]' },
    ],
  },

  // ── POST 24 ─────────────────────────────────────────────────────────────
  {
    title: 'Whiplash Injury: Road Accident Recovery Guide',
    slug: 'whiplash-injury-road-accident-recovery-guide',
    excerpt:
      'Whiplash is one of the most common road accident injuries. Early physiotherapy within days of injury leads to faster recovery and prevents chronic pain.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Neuro & Paediatric'],
    tags: ['neck pain', 'neurological', 'rehabilitation', 'manual therapy'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist treating patient neck after whiplash injury, gentle manual therapy technique',
    stock_search_keywords: ['whiplash physiotherapy', 'neck injury after accident', 'cervical whiplash treatment'],
    content: [
      h2('What Is Whiplash?'),
      p('[OUTLINE: 150 words — mechanism of injury, acceleration-deceleration, tissue damage]'),
      h2('Symptoms of Whiplash'),
      ul('[LIST ITEM: neck pain and stiffness]', '[LIST ITEM: headaches originating at skull base]', '[LIST ITEM: dizziness and visual disturbance]', '[LIST ITEM: arm pain and tingling]', '[LIST ITEM: cognitive symptoms (concentration, memory)]'),
      h2('WAD Classification (Whiplash Associated Disorder)'),
      p('[OUTLINE: 150 words — Grade I–IV, prognostic significance]'),
      h2('Why Early Physiotherapy Matters for Whiplash'),
      p('[OUTLINE: 200 words — evidence for early mobilisation over rest, chronic pain prevention, yellow flags]'),
      h2('Physiotherapy Treatment for Whiplash'),
      p('[OUTLINE: 200 words — active vs passive treatment, manual therapy, exercise, pain education, graded activity]'),
      h2('Returning to Normal Activities'),
      p('[OUTLINE: 150 words — activity grading, driving, work return, sport]'),
      h2('Preventing Chronic Whiplash Syndrome'),
      p('[OUTLINE: 150 words — psychological factors, graded exposure, avoiding catastrophisation]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'How long does whiplash recovery take?', answer: '[FILL]' },
      { question: 'Should I wear a neck collar after whiplash?', answer: '[FILL]' },
      { question: 'When should I see a physiotherapist after a road accident?', answer: '[FILL]' },
      { question: 'Can whiplash cause permanent damage?', answer: '[FILL]' },
      { question: 'Is physiotherapy better than rest for whiplash?', answer: '[FILL]' },
    ],
  },

  // ── POST 25 ─────────────────────────────────────────────────────────────
  {
    title: 'Scoliosis: Can Physiotherapy Help?',
    slug: 'scoliosis-can-physiotherapy-help',
    excerpt:
      'Scoliosis causes an abnormal lateral curve in the spine. Physiotherapy and exercise therapy can slow progression, reduce pain, and improve quality of life.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Back & Spine'],
    tags: ['spine', 'posture', 'paediatric', 'rehabilitation'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist assessing teenage patient spine for scoliosis with Adam forward bend test',
    stock_search_keywords: ['scoliosis physiotherapy', 'scoliosis exercises', 'spinal curve treatment'],
    content: [
      h2('What Is Scoliosis?'),
      p('[OUTLINE: 150 words — lateral curvature definition, Cobb angle, structural vs functional types]'),
      h2('Types of Scoliosis'),
      ul('[LIST ITEM: idiopathic adolescent scoliosis (most common)]', '[LIST ITEM: congenital scoliosis]', '[LIST ITEM: neuromuscular scoliosis (cerebral palsy, muscular dystrophy)]', '[LIST ITEM: degenerative adult scoliosis]'),
      h2('How Scoliosis Is Assessed'),
      p('[OUTLINE: 150 words — Adam forward bend test, Cobb angle on X-ray, trunk rotation measurement]'),
      h2('Can Physiotherapy Treat Scoliosis?'),
      p('[OUTLINE: 200 words — SOSORT evidence, Schroth method, SEAS method, curve stabilisation]'),
      h2('Schroth Method for Scoliosis'),
      p('[OUTLINE: 200 words — 3D corrective breathing, postural correction, curve-specific exercises]'),
      h2('When Is Surgery or Bracing Recommended?'),
      p('[OUTLINE: 150 words — Cobb angle thresholds, bracing for adolescents 20–45°, surgery >45°]'),
      h2('Physiotherapy for Adult Degenerative Scoliosis'),
      p('[OUTLINE: 150 words — pain management, core stability, posture, surgical adjunct rehab]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'Can scoliosis be corrected without surgery?', answer: '[FILL]' },
      { question: 'What is the Schroth method for scoliosis?', answer: '[FILL]' },
      { question: 'At what angle of scoliosis is surgery needed?', answer: '[FILL]' },
      { question: 'Can adults with scoliosis benefit from physiotherapy?', answer: '[FILL]' },
      { question: 'Does scoliosis get worse with age?', answer: '[FILL]' },
    ],
  },

  // ── POST 26 ─────────────────────────────────────────────────────────────
  {
    title: 'Arthritis Management Through Physiotherapy',
    slug: 'arthritis-management-physiotherapy',
    excerpt:
      'Arthritis is not a reason to stop moving — it is a reason to move smarter. Physiotherapy reduces joint pain and maintains function for arthritis patients of all ages.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Health & Lifestyle'],
    tags: ['arthritis', 'joints', 'exercise therapy', 'rehabilitation'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Elderly patient performing physiotherapy exercises for knee arthritis, clinical gym setting',
    stock_search_keywords: ['arthritis physiotherapy', 'physiotherapy for joint pain', 'osteoarthritis treatment'],
    content: [
      h2('Types of Arthritis That Physiotherapy Treats'),
      p('[OUTLINE: 150 words — osteoarthritis (OA), rheumatoid arthritis (RA), psoriatic arthritis, gout]'),
      h2('Why Exercise Is the Best Medicine for Arthritis'),
      p('[OUTLINE: 200 words — cartilage nutrition, muscle protection of joints, pain neuroscience, fear avoidance cycle]'),
      h2('Physiotherapy Assessment for Arthritis'),
      p('[OUTLINE: 150 words — joint ROM, muscle strength, functional capacity, pain and fatigue levels]'),
      h2('Exercise Therapy for Osteoarthritis'),
      p('[OUTLINE: 200 words — aerobic exercise, hydrotherapy, strength training, OARSI guidelines]'),
      h2('Managing Rheumatoid Arthritis with Physiotherapy'),
      p('[OUTLINE: 150 words — disease activity monitoring, joint protection, splinting, energy conservation]'),
      h2('Electrotherapy and Modalities for Arthritis Pain'),
      p('[OUTLINE: 150 words — TENS, ultrasound, heat/cold therapy — adjunct role]'),
      h2('Self-Management Strategies'),
      p('[OUTLINE: 150 words — weight management, activity pacing, assistive devices, water exercise]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'Does exercise make arthritis worse?', answer: '[FILL]' },
      { question: 'Is swimming good for arthritis?', answer: '[FILL]' },
      { question: 'Can physiotherapy replace medication for arthritis?', answer: '[FILL]' },
      { question: 'What is the best exercise for knee osteoarthritis?', answer: '[FILL]' },
      { question: 'Should I apply heat or ice to arthritic joints?', answer: '[FILL]' },
    ],
  },

  // ── POST 27 ─────────────────────────────────────────────────────────────
  {
    title: 'Breathing Exercises for COPD and Respiratory Conditions',
    slug: 'breathing-exercises-copd-respiratory-conditions',
    excerpt:
      'Chest physiotherapy and breathing exercises can dramatically improve quality of life for patients with COPD and other chronic respiratory conditions.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Neuro & Paediatric'],
    tags: ['copd', 'respiratory', 'physiotherapy', 'exercise therapy'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Patient performing breathing exercises with physiotherapist guidance, clinical pulmonary rehab setting',
    stock_search_keywords: ['breathing exercises COPD', 'chest physiotherapy', 'pulmonary rehabilitation'],
    content: [
      h2('What Is COPD and How Does It Affect Breathing?'),
      p('[OUTLINE: 150 words — COPD definition, airflow limitation, mucus hypersecretion, exertional dyspnoea]'),
      h2('How Physiotherapy Helps COPD'),
      p('[OUTLINE: 200 words — pulmonary rehabilitation evidence, exercise capacity improvement, hospitalisation reduction]'),
      h2('Breathing Techniques for COPD'),
      h3('Pursed Lip Breathing'),
      p('[OUTLINE: 100 words — technique, how it helps slow exhalation and reduce air trapping]'),
      h3('Diaphragmatic Breathing'),
      p('[OUTLINE: 100 words — technique, reduces accessory muscle use, improves breathing efficiency]'),
      h3('Active Cycle of Breathing Technique (ACBT)'),
      p('[OUTLINE: 150 words — breathing control, thoracic expansion exercises, forced expiration — clearing secretions]'),
      h2('Exercise Training for COPD'),
      p('[OUTLINE: 200 words — aerobic training, interval training for severe COPD, strength training, Borg scale]'),
      h2('Postural Drainage and Airway Clearance'),
      p('[OUTLINE: 150 words — gravity-assisted positions, manual techniques, Flutter/Acapella devices]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'Can physiotherapy reverse COPD?', answer: '[FILL]' },
      { question: 'How many breathing exercises should I do per day for COPD?', answer: '[FILL]' },
      { question: 'Is walking good for COPD patients?', answer: '[FILL]' },
      { question: 'What is pulmonary rehabilitation?', answer: '[FILL]' },
      { question: 'Can breathing exercises improve oxygen levels?', answer: '[FILL]' },
    ],
  },

  // ── POST 28 ─────────────────────────────────────────────────────────────
  {
    title: 'Physiotherapy for Headaches and Migraines',
    slug: 'physiotherapy-headaches-migraines',
    excerpt:
      'Not all headaches originate in the head. Cervicogenic and tension headaches respond extremely well to physiotherapy targeting the neck and upper thoracic spine.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Neuro & Paediatric'],
    tags: ['headache', 'neck pain', 'neurological', 'manual therapy'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist performing upper cervical joint mobilisation for headache treatment, clinical setting',
    stock_search_keywords: ['physiotherapy for headaches', 'cervicogenic headache treatment', 'neck headache physiotherapy'],
    content: [
      h2('Types of Headaches Physiotherapy Treats'),
      ul('[LIST ITEM: cervicogenic headache (from neck joint dysfunction)]', '[LIST ITEM: tension-type headache]', '[LIST ITEM: headache associated with temporomandibular joint (TMJ) dysfunction]', '[LIST ITEM: post-concussion headache]'),
      h2('Understanding Cervicogenic Headaches'),
      p('[OUTLINE: 200 words — C1–C3 joint referral patterns, Watson headache approach, diagnosis criteria]'),
      h2('Why Physiotherapy Works for Headaches'),
      p('[OUTLINE: 200 words — upper cervical joint mobilisation evidence, trigger point treatment, deep neck flexor retraining]'),
      h2('Physiotherapy Assessment for Headache'),
      p('[OUTLINE: 150 words — cervical ROM, headache diary, cranio-cervical flexion test, neurological screen]'),
      h2('Physiotherapy Techniques for Headache'),
      p('[OUTLINE: 200 words — upper cervical mobilisation, suboccipital soft tissue release, postural correction, home exercises]'),
      h2('Migraine: Can Physiotherapy Help?'),
      p('[OUTLINE: 150 words — migraine as neurological condition, physiotherapy role in triggers, comorbid neck pain]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'What is a cervicogenic headache?', answer: '[FILL]' },
      { question: 'Can neck problems cause daily headaches?', answer: '[FILL]' },
      { question: 'How many physiotherapy sessions are needed for headaches?', answer: '[FILL]' },
      { question: 'Can physiotherapy cure migraines?', answer: '[FILL]' },
      { question: 'What exercises help tension headaches?', answer: '[FILL]' },
    ],
  },

  // ── POST 29 ─────────────────────────────────────────────────────────────
  {
    title: 'Balance Disorders and Vestibular Physiotherapy',
    slug: 'balance-disorders-vestibular-physiotherapy',
    excerpt:
      'Dizziness and balance problems significantly impact quality of life. Vestibular physiotherapy offers highly effective, evidence-based treatment for most vestibular conditions.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 7,
    ranchi_reference: false,
    categories: ['Neuro & Paediatric'],
    tags: ['balance', 'vestibular', 'neurological', 'rehabilitation'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist performing Epley manoeuvre on patient for BPPV, clinical treatment room',
    stock_search_keywords: ['vestibular physiotherapy', 'BPPV treatment physiotherapy', 'dizziness physiotherapy'],
    content: [
      h2('The Vestibular System: Your Built-In Balance Sensor'),
      p('[OUTLINE: 150 words — semicircular canals, otoliths, vestibulo-ocular reflex, proprioception integration]'),
      h2('Common Vestibular Conditions'),
      ul('[LIST ITEM: BPPV (Benign Paroxysmal Positional Vertigo)]', '[LIST ITEM: vestibular neuritis]', '[LIST ITEM: labyrinthitis]', '[LIST ITEM: central vestibular disorders]', '[LIST ITEM: age-related vestibular decline (presbyvestibulopathy)]'),
      h2('Diagnosing BPPV: The Dix-Hallpike Test'),
      p('[OUTLINE: 150 words — test procedure, nystagmus patterns, canal identification]'),
      h2('The Epley Manoeuvre: Treating BPPV in Minutes'),
      p('[OUTLINE: 200 words — step-by-step procedure, success rate >80% in one session, self-Epley option]'),
      h2('Vestibular Rehabilitation Therapy (VRT)'),
      p('[OUTLINE: 200 words — gaze stabilisation exercises, balance training, habituation exercises, central compensation]'),
      h2('How Long Does Vestibular Physiotherapy Take?'),
      p('[OUTLINE: 150 words — BPPV often 1–3 sessions, chronic vestibular 6–12 weeks, factors affecting prognosis]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'What is the Epley manoeuvre and does it work?', answer: '[FILL]' },
      { question: 'How do I know if my dizziness is coming from my ear or brain?', answer: '[FILL]' },
      { question: 'Can vestibular physiotherapy cure BPPV?', answer: '[FILL]' },
      { question: 'What exercises help vestibular rehabilitation at home?', answer: '[FILL]' },
      { question: 'Is dizziness a reason to see a physiotherapist or a doctor first?', answer: '[FILL]' },
    ],
  },

  // ── POST 30 ─────────────────────────────────────────────────────────────
  {
    title: 'How Often Should You See a Physiotherapist?',
    slug: 'how-often-should-you-see-physiotherapist',
    excerpt:
      'Session frequency is one of the most common questions patients ask. The honest answer depends on your condition, goals, and how actively you engage with your home programme.',
    seo_title: '// FILL: ~60 chars',
    seo_description: '// FILL: ~155 chars',
    reading_time: 6,
    ranchi_reference: false,
    categories: ['Physiotherapy Basics'],
    tags: ['physiotherapy', 'physiotherapy basics', 'rehabilitation'],
    featured_image_alt: '// FILL: descriptive alt text',
    featured_image_suggestion: 'Physiotherapist and patient reviewing treatment plan calendar together, warm clinical setting',
    stock_search_keywords: ['how often physiotherapy', 'physiotherapy session frequency', 'physiotherapy treatment plan'],
    content: [
      h2('There Is No One-Size-Fits-All Answer'),
      p('[OUTLINE: 150 words — individualised treatment planning, condition-dependent, patient compliance factor]'),
      h2('Acute Injuries: Higher Frequency Early On'),
      p('[OUTLINE: 150 words — 2–3 sessions per week in acute phase, then reduce as healing progresses]'),
      h2('Chronic Conditions: Consistency Over Intensity'),
      p('[OUTLINE: 150 words — 1 session per week or fortnight, focus on self-management]'),
      h2('Post-Surgical Rehabilitation: Protocol-Driven'),
      p('[OUTLINE: 150 words — surgeon protocol, hospital vs outpatient, phase-based frequency]'),
      h2('Neurological Conditions: More Frequent for Longer'),
      p('[OUTLINE: 150 words — stroke, CP — daily if possible in early phases, neuroplasticity window]'),
      h2('The Home Programme: Where the Real Progress Happens'),
      p('[OUTLINE: 200 words — in-clinic is 1 hour per week, home is the other 167 hours — compliance is key]'),
      h2('When Can You Stop Physiotherapy?'),
      p('[OUTLINE: 150 words — functional goals met, independent self-management, when to return for check-up]'),
      h2('Preventive Physiotherapy: Annual Check-Ups'),
      p('[OUTLINE: 100 words — like a dental check-up for your musculoskeletal system, screen for issues early]'),
      h2('Conclusion'),
      p('[OUTLINE: 80 words — CTA]'),
    ],
    faqs: [
      { question: 'Can I see a physiotherapist just once?', answer: '[FILL]' },
      { question: 'How do I know when to stop physiotherapy?', answer: '[FILL]' },
      { question: 'Is physiotherapy once a week enough?', answer: '[FILL]' },
      { question: 'What if I cannot afford frequent physiotherapy sessions?', answer: '[FILL]' },
      { question: 'Should I continue physiotherapy if I feel better after 2 sessions?', answer: '[FILL]' },
    ],
  },
]

// ── Seed Function ─────────────────────────────────────────────────────────

export async function seedBlogPostsModeB(): Promise<void> {
  console.log('\n[blog-mode-b] Seeding 30 outline blog posts as drafts…')
  let count = 0
  for (const post of postsModeB) {
    const { categories, tags, featured_image_suggestion, stock_search_keywords, ...rest } = post

    // Resolve category IDs
    const categoryIds = categories.map((name: string) => getId('category', name))

    // Resolve tag IDs
    const tagIds = tags.map((name: string) => getId('tag', name))

    await createDraft(
      'blog-post',
      {
        ...rest,
        categories: categoryIds,
        tags: tagIds,
      }
    )
    count++
    console.log(`  ✓ [${count}/30] DRAFT "${post.title}"`)
  }
  console.log(`  → Mode B: ${count} outline drafts created (unpublished)`)
}
